# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'
  
- script: |
    npm run build
  displayName: 'npm build'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Start-Process powershell -ArgumentList 'New-Item -ItemType SymbolicLink -Path ".\node" -Target "C:\agent\_work\_tool\node"' -Verb RunAs
      
      # New-Item -ItemType SymbolicLink -Path ".\node" -Target "C:\agent\_work\_tool\node"
  displayName: 'create symlink'

- script: |
    npm test
  displayName: 'npm test'
